name: github pages

on:
  push:
    branches:
      - book
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        shell: bash
        run: |
          wget https://gilmi.me/static/misc/mymdbook2
          chmod +x mymdbook2
          ./mymdbook2 build
          cp assets/book-logo.png book/
          cp assets/book-logo-transparent.png book/
          cp assets/pdf.png book/
          cp lhbg-v0.pdf book/
          echo "learn-haskell.blog" > book/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/book'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
